### ISSUE TITLE
Upcoming version; -exclude option

### ISSUE THREAD

**Issue by madeddie** [johnbellone/consul-replicate-cookbook#5]
The current master branch of consul-replicate has an -exclude option, which is very useful in conjunction with vault in a multi DC setup. (most of the `vault/` tree needs to be replicated, but some specific keys shouldn't).

This option is not available in the latest release, nor in older versions, but I'll be running off of the master branch myself.

Would you consider adding the -exclude option as config file setting? If so, I'll make a PR.

**Comment by johnbellone** [comment]
@madeddie PR are absolutely welcome!
